Vagrant.configure("2") do |config|
  config.vm.box = "elastic/ubuntu-16.04-x86_64"
  config.vm.box_version = "20180210.0.0"

  config.vm.provider :libvirt do |libvirt|
    libvirt.cpus = 4
    libvirt.memory = 32 * 1024
    libvirt.storage :file, :size => "60G"
    libvirt.nested = true
    libvirt.cpu_mode = 'host-passthrough'
  end

  config.vm.define :devstack do |devstack|
      devstack.vm.hostname = 'devstack'
      devstack.vm.network :private_network, :ip => '55.55.55.6', :type => :static
  end

  config.vm.network "forwarded_port", guest: 8080, host: 8080

  if Vagrant.has_plugin?("vagrant-proxyconf")
    config.proxy.http     = ENV['http_proxy']
    config.proxy.https    = ENV['https_proxy']
    config.proxy.no_proxy = ENV['no_proxy']
  end

  #config.vm.provision "docker"

end

# Portforwarding command for forwarding 8080:
# ssh -L 8080:<libvirt_vm_ip>:8080 <physical_server_username>@<physical_server_ip>
